#include "led.h"

void LED_Init(void)
{
    //GPIOA INIT
    GPIO_InitTypeDef GPIO_INITSCRUCTURE1;
    RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOA|RCC_AHB1Periph_GPIOE, ENABLE);
    GPIO_INITSCRUCTURE1.GPIO_Pin   = GPIO_Pin_6|GPIO_Pin_7;
    GPIO_INITSCRUCTURE1.GPIO_Mode  = GPIO_Mode_OUT;
    GPIO_INITSCRUCTURE1.GPIO_OType = GPIO_OType_PP;
    GPIO_INITSCRUCTURE1.GPIO_PuPd  = GPIO_PuPd_UP;
    GPIO_INITSCRUCTURE1.GPIO_Speed = GPIO_Speed_50MHz;
    GPIO_Init(GPIOA,&GPIO_INITSCRUCTURE1);

    //SET GPIOA INIT UP (LED TURN OFF)
    GPIO_SetBits (GPIOA,GPIO_Pin_6 | GPIO_Pin_7);
}
